export const LOAD_NEWS_DATA = 'LOAD_NEWS_DATA'
export const LOAD_NEWS_DATA_ERROR = 'LOAD_NEWS_DATA_ERROR'

export const LOAD_USER_DATA = 'LOAD_USER_DATA'
export const LOAD_USER_DATA_ERROR = 'LOAD_USER_DATA_ERROR'

export const ALERT_SHOW = 'ALERT_SHOW'
export const ALERT_HIDE = 'ALERT_HIDE'
export const ALERT_RESET = 'ALERT_RESET'

export const MODAL_SHOW = 'MODAL_SHOW'
export const MODAL_HIDE = 'MODAL_HIDE'
export const MODAL_RESET = 'MODAL_RESET'
export const MODAL_UPDATE = 'MODAL_UPDATE'